//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServicePhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPackage
    {
        public int fldPackageID { get; set; }
        public string fldPackageType { get; set; }
        public decimal fldPackageCost { get; set; }
    }
}
